### PR TITLE
Meetbout

### PR DESCRIPTION
**Pull request by Vegter**
Allow for meetbouten in the Storage

### CODE REVIEW

**Comment by Vegter** [comment]
This branch is derived from create-database

**Comment by dolhuis** [comment]
In this project I see overlap in what GOB-Upload does. In a way this project uses some GOB specific knowledge, and a dataset-definition (which could/should(?) also be shared among services) to do a one-off instantiation of the tables.

In the same way initialization of queues could be done by the GOB-Worfklow service. GOB-Storage and GOB-Upload could be integrated, they are both about managing the underlying storage (this one one a one-off meta level, GOB-Uploa on the dataplane.) Migrations could also by implemented in the integrated project.

**Comment by Vegter** [comment]
OK!

**Comment by dolhuis** [comment]
> OK!

Nice, I will set about it, then.

**Pull request merged**
